In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_openml
boston = fetch_openml(name="boston", version=1, as_frame=True, parser="pandas")

In [9]:
boston

{'data':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT
 0       15.3  396.90   4.98
 1       17.8  396.90   9.14
 2       17.8  392.83   4.03
 3       18.7  394.63   2.94
 4       18.7  396.90   5.33
 ..       ...     ...    ...
 501     21.0  391.99   9.67
 502     21.0  396.90   9.08
 503     21.0  396.90   5.64
 504     21.0  393.45   6.48
 505     21.0  396.90   7.88

 [506 rows x 13 columns],
 'target': 0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ...
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
 'frame':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT  MEDV
 0       15.3  396.90   4.98  24.0
 1       17.8  396.90   9.14  21.6
 2       17.8  392.83   4.03  34.7
 3       18.7  394.63   2.94  33.4
 4       18.7  396.90   5.33  36.2
 ..       ...     ...    ...   ...
 501     21.0  391.99   9.67  22.4
 502     21.0  396.90   9.08  20.6
 503     21.0  396.90   5.64  23.9
 504     21.0  393.45   6.48  22.0
 505     21.0  396.90   7.88  11.9

 [506 rows x 14 columns],
 'categories': None,
 'feature_names': ['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 'target_names': ['MEDV'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.",
 'details': {'id': '531',
  'name': 'boston',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"],
  'collection_date': '1978',
  'upload_date': '2014-09-29T00:08:07',
  'language': 'English',
  'licence': 'Public',
  'url': 'https://openml.org/data/v1/download/52643/boston.arff',
  'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq',
  'file_id': '52643',
  'default_target_attribute': 'MEDV',
  'tag': ['Data Science',
   'Housing Economics',
   'Kaggle',
   'OpenML-Reg19',
   'study_130',
   'Urban Studies'],
  'visibility': 'public',
  'status': 'active',
  'processing_date': '2020-11-20 20:16:37',
  'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'},
 'url': 'https://www.openml.org/d/531'}

In [10]:
df = boston.frame
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [13]:
df.sample()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
434,13.9134,0.0,18.1,0,0.713,6.208,95.0,2.2222,24,666.0,20.2,100.63,15.17,11.7

In [14]:
df["price"] = boston.target

In [15]:
df.sample()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,price
85,0.05735,0.0,4.49,0,0.449,6.63,56.1,4.4377,3,247.0,18.5,392.3,6.53,26.6,26.6

In [20]:
# EDA
print(df.shape)
print(df.columns)
print(df.info())
print(df.isnull().sum())

(506, 15)
Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV', 'price'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    category
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    category
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
 14  price    506 non-null    float64
dtypes: category(2), float64(13)
memory usage: 53.0 KB
None
CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
price      0
dtype: int64

In [21]:
df.corr()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,price
CRIM,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305,-0.388305
ZN,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445,0.360445
INDUS,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725,-0.483725
CHAS,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260,0.175260
NOX,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321,-0.427321
RM,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360,0.695360
AGE,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955,-0.376955
DIS,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929,0.249929
RAD,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626,-0.381626
TAX,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536,-0.468536
PTRATIO,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787,-0.507787
B,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461,0.333461
LSTAT,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663,-0.737663
MEDV,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000,1.000000
price,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000,1.000000

In [22]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [23]:
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [24]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: price, dtype: float64

In [ ]:
# if u have categorical data then convert into numeric
# if u have combination of int, float, other then convert float
X = X.astype(float)
y = y.astype(float)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(404, 14)
(102, 14)
(404,)
(102,)

In [29]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

In [30]:
model = LinearRegression()
model

LinearRegression()

In [32]:
mse = cross_val_score(model, X, y, scoring="neg_mean_squared_error", cv=5)

In [33]:
mse

array([-4.72543150e-28, -7.76489067e-28, -9.24763675e-29, -8.40074380e-28,
       -4.83452234e-27])

In [34]:
mean_mse = np.mean(mse)
mean_mse

np.float64(-1.403221061275301e-27)

In [35]:
model.fit(X_train, y_train)

LinearRegression()

In [36]:
y_pred = model.predict(X_test)
y_pred

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4])

In [37]:
compare_df = pd.DataFrame({
    "Actual" : y_test,
    "Predicted" : y_pred
})

compare_df

     Actual  Predicted
173    23.6       23.6
274    32.4       32.4
491    13.6       13.6
72     22.8       22.8
452    16.1       16.1
..      ...        ...
412    17.9       17.9
436     9.6        9.6
411    17.2       17.2
86     22.5       22.5
75     21.4       21.4

[102 rows x 2 columns]